sudo: required
services: 
  - docker

before_install:
  - docker build -t artem/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true artem/docker-react npm run test -- --coverage

 deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "Docker-frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-355260478413"
  bucket_path: "docker-frontend"
  on:
   branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"